# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = ["github.com/google/subcommands", "github.com/buildpack/lifecycle", "github.com/docker/distribution"]

[[constraint]]
  name = "github.com/cloudfoundry/libbuildpack"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  revision = "v1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  branch = "master"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/jarcoal/httpmock.v1"

[[override]]
  name = "github.com/elazarl/goproxy"
  revision = "aacba83f36a55ac31cbb71c06547a328c0cd1604"

[[constraint]]
  branch = "master"
  name = "github.com/buildpack/libbuildpack"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/libjavabuildpack"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[override]]
  name = "github.com/google/go-containerregistry"
  revision = "74aef1a35cfa25a5a20c951199abd26356e7bead"
