[[groups]]
labels = ["nodejs"]
buildpacks = [
  { id = "org.cloudfoundry.buildpacks.nodejs-compat", version = "latest", optional = true },
  { id = "org.cloudfoundry.buildpacks.nodejs", version = "latest" },
  { id = "org.cloudfoundry.buildpacks.yarn", version = "latest" }
]

[[groups]]
labels = ["nodejs"]
buildpacks = [
  { id = "org.cloudfoundry.buildpacks.nodejs-compat", version = "latest", optional = true },
  { id = "org.cloudfoundry.buildpacks.nodejs", version = "latest" },
  { id = "org.cloudfoundry.buildpacks.npm", version = "latest" },
]