[[groups]]
labels = ["node-engine", "yarn"]
buildpacks = [
  { id = "org.cloudfoundry.nodejs-compat", version = "latest", optional = true },
  { id = "org.cloudfoundry.node-engine", version = "latest" },
  { id = "org.cloudfoundry.yarn", version = "latest" }
]

[[groups]]
labels = ["node-engine", "npm"]
buildpacks = [
  { id = "org.cloudfoundry.nodejs-compat", version = "latest", optional = true },
  { id = "org.cloudfoundry.node-engine", version = "latest" },
  { id = "org.cloudfoundry.npm", version = "latest" }
]
